version: '3'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql_5.6
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
      MYSQL_DATABASE: "development_docker"
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      TZ: "Asia/Tokyo"
    command: --character-set-server=cp932, --default-storage-engine=innodb